databases:
  - name: project-database
    plan: free
    region: frankfurt

services:
  - type: web
    name: nodejs-app
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: cd esgi.4a.render.nodejs && npm install
    startCommand: cd esgi.4a.render.nodejs && npm run start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: project-database
          property: connectionString
