databases:
  - name: project-database
    databaseName: app_database
    user: app_user
    plan: free
    region: frankfurt

services:
  - type: web
    name: nodejs-app
    plan: free
    buildCommand: cd esgi.4a.render.static && npm install
    startCommand: cd esgi.4a.render.static && npm run start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: project-database
          property: connectionString
    runtime: node
